site_name: Multicatyl Dokumentation
site_url: https://hahn1315.github.io/Multicatyl/
copyright: Multicatyl – MIT-Lizenz. Übersetzungen basieren auf GermanDactyl (Paul Schwarz, MIT).

repo_name: Multicatyl
repo_url: https://github.com/hahn1315/Multicatyl
edit_uri: edit/main/docs/

theme:
  name: material
  language: de
  logo: assets/images/logo.png
  features:
    - toc.integrate
    - content.code.annotate
  favicon: assets/images/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Zum dunklen Modus wechseln
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Zum hellen Modus wechseln

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hahn1315/Multicatyl

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Start: index.md
  - Versionsverwaltung: manager/index.html
  - Installation: installation.md
  - Deinstallation: uninstall.md
  - Anleitungen:
      - Update ausführen: guides/update.md
      - Übersetzungen einreichen: guides/contribute.md
  - Fehlerbehebung: troubleshooting.md
  - FAQ: faq.md
